ISSUE106-UPDATE-get-schedule
Selody-project/Backend pull request #111
Opened 2023-06-25 09:00 UTC by GGANCC1

# 설명

- #106 
- getUserPersonalSchedule 호출 시, PersonalSchedule Table, Group Table에서 유저의 일정에 해당하는 모든 레코드를 호출
- getGroupSchedule에도 동일 적용.
- End Point 변경 : `api/user/{user_id}/calendar`  => `api/user/calendar` 로 변경
- getSchedule(id, start, end)에서 id로 하나의 integer만을 받던 기존의 방식을 수정, **id에 배열을 담아 보내도록 함.**
- update test code
- update swagger

# 테스트

- Integraion Test

2023-06-25 15:45 UTC, Taehoya requested changes

2023-06-25 15:45 UTC, Taehoya commented on src/routes/auth.js
> +router.post('/db', dbSetUp);
혹시 이 코드에 대해서 설명해주실 수 있을까요?

2023-06-25 20:10 UTC, GGANCC1 commented on src/routes/auth.js
> +router.post('/db', dbSetUp);
직접 하나씩 테스트 할 때 데이터셋 한번에 넣으려고 썼던 코드인데, 지우는걸 깜빡했네요. 지우고 다시 올릴게요.

2023-06-27 18:22 UTC, Taehoya reviewed
혹시 testcase에
/api/user/calendar 일때는 group event 나오고
/api/group/calendar일때 user event 나오는 경우를 추가해주실 수 있을까요?

2023-07-01 19:04 UTC, GGANCC1 commented
> 혹시 testcase에 /api/user/calendar 일때는 group event 나오고 /api/group/calendar일때 user event 나오는 경우를 추가해주실 수 있을까요?

네, 추가하였습니다. 
그룹 A, B, C가 있고 유저 1, 2, 3이 있다고 할 때, 그룹 구성원은 아래와 같이 설정하였습니다.
- 그룹 A 구성원 : 1, 2
- 그룹 B 구성원 : 1, 2
- 그룹 C 구성원 : 3

이때, 추가된 테스트 케이스에서 확인하는 부분은 아래와 같습니다
- 유저 1의 개인 일정 조회에서 그룹 A, B의 GroupSchedule Table의 일정을 제대로 가져오는지.
- 그룹 C의 일정을 가져오지는 않는지 확인. (그룹 C의 일정은 조회되어서는 안되므로.)
- 그룹 1의 그룹 일정 조회에서 유저 1, 2의 PersonalSchedule Table의 일정을 제대로 가져오는지.
- 유저 3의 일정을 가져오지는 않는지 확인. (유저 3의 일정은 조회되어서는 안되므로.)

2023-07-01 19:48 UTC, GGANCC1 commented
> 혹시 testcase에 /api/user/calendar 일때는 group event 나오고 /api/group/calendar일때 user event 나오는 경우를 추가해주실 수 있을까요?

네, 추가하였습니다. 
그룹 A, B, C가 있고 유저 1, 2, 3이 있다고 할 때, 그룹 구성원은 아래와 같이 설정하였습니다.
- 그룹 A 구성원 : 1, 2
- 그룹 B 구성원 : 1, 2
- 그룹 C 구성원 : 3

이때, 추가된 테스트 케이스에서 확인하는 부분은 아래와 같습니다
- 유저 1의 개인 일정 조회에서 유저 1의 개인 일정과 더불어 그룹 A, B의 GroupSchedule Table의 일정을 제대로 가져오는지.
- 그룹 C의 일정을 가져오지는 않는지 확인. (그룹 C의 일정은 조회되어서는 안되므로.)
- 그룹 1의 그룹 일정 조회에서 그룹 1의 그룹 일정과 더불어 유저 1, 2의 PersonalSchedule Table의 일정을 제대로 가져오는지.
- 유저 3의 일정을 가져오지는 않는지 확인. (유저 3의 일정은 조회되어서는 안되므로.)

2023-07-02 01:23 UTC, Taehoya approved these changes

2023-07-02 08:24 UTC, merged