Back task social login
Selody-project/Backend pull request #91
Opened 2023-06-08 01:23 UTC by joseph0926

# 설명

- #ISSUE
- 구글 & 네이버 로그인 구현

# 테스트

- x

2023-06-08 03:08 UTC, Taehoya requested changes

2023-06-08 03:08 UTC, Taehoya commented on src/controllers/auth.js
> +    return res.status(400).json({ message: '액세스 토큰이 필요합니다.' });
https://github.com/Selody-project/Backend/blob/main/src/middleware/token.js#L57
혹시 이거 참고해서 이렇게 변경해주실 수 있을까요?

2023-06-08 03:08 UTC, Taehoya commented on src/controllers/auth.js
> +    console.log(error);
불필요한 console는 지우는게 좋을거 같아요. 지워주실 수 있을까요?

2023-06-08 03:08 UTC, Taehoya reviewed
commit 메시지에 asdsa라는 메시지가 있는데 혹시 squash나 조금 더 의미있는 message로 변경해주실 수 있을까요?

2023-06-08 03:10 UTC, Taehoya requested changes

2023-06-08 03:10 UTC, Taehoya commented on src/controllers/auth.js
> +      return res.status(401).json({ message: '토큰이 유효하지 않습니다.' });
https://github.com/Selody-project/Backend/blob/main/src/middleware/token.js#L57
혹시 이거 참고해서 이렇게 변경해주실 수 있을까요?

2023-06-09 00:35 UTC, joseph0926 commented on src/controllers/auth.js
> +    console.log(error);
> 불필요한 console는 지우는게 좋을거 같아요. 지워주실 수 있을까요?

엇 이부분은 제가 수정한게 아니라서,, 그래도 삭제할까요??

2023-06-09 00:43 UTC, joseph0926 commented on src/controllers/auth.js
> +    return res.status(400).json({ message: '액세스 토큰이 필요합니다.' });
> https://github.com/Selody-project/Backend/blob/main/src/middleware/token.js#L57 혹시 이거 참고해서 이렇게 변경해주실 수 있을까요?

수정했습니다!

2023-06-09 04:15 UTC, Taehoya commented on src/controllers/auth.js
> +    console.log(error);
네 지워주실 수 있을까요?

2023-06-13 02:53 UTC, Taehoya approved these changes

2023-06-13 04:29 UTC, merged